name: prebuild&publish

on:
  push:
    tags: # should read v0.5.1-rc ie <moonbeam version><optional custom suffix>
      - 'v*'

jobs:
  prerelease:
    runs-on: ubuntu-20.04
    steps:
      - name: get the current version tag for moonbeam-binary
        run: |
          pushed_tag=${GITHUB_REF/refs\/tags\//}
          echo "[DEBUG] MOONBEAM_BINARY_TAG=$pushed_tag"
          echo "MOONBEAM_BINARY_TAG=$pushed_tag" >> $GITHUB_ENV

      - name: pre release draft
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.MOONBEAM_BINARY_TAG }}
          release_name: ${{ env.MOONBEAM_BINARY_TAG }}
          draft: true
          prerelease: true

      - name: prep a release upload url artifact
        run: |
          release_upload_url=${{ steps.create_release.outputs.upload_url }}
          echo "[DEBUG] release upload url $release_upload_url"
          echo "$release_upload_url" > ./release_upload_url.txt

      - name: upload the release upload url artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: release_upload_url
          path: ./release_upload_url.txt

  prebuild:
    needs: prerelease
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: # windows wormholes are not supported
        os:
          - ubuntu-20.04
          - macos-10.15
    steps:
      - name: get the current version tag for moonbeam-binary and moonbeam
        run: |
          pushed_tag=${GITHUB_REF/refs\/tags\//} # rm the 'refs/tags/' prefix
          unprefixed_tag=${pushed_tag#v} # rm the leading 'v'
          moonbeam_tag=${unprefixed_tag%-*} # rm the dash suffix
          echo "[DEBUG] MOONBEAM_BINARY_TAG=$pushed_tag"
          echo "[DEBUG] MOONBEAM_TAG=$moonbeam_tag"
          echo "MOONBEAM_BINARY_TAG=$pushed_tag" >> $GITHUB_ENV
          echo "MOONBEAM_TAG=$moonbeam_tag" >> $GITHUB_ENV

      - name: checkout the moonbeam repo
        uses: actions/checkout@v2.3.4
        with:
          repository: PureStake/moonbeam
          ref: ${{ env.MOONBEAM_TAG }}
          path: ./moonbeam

      - name: substrate prerequisites & moonbeam init
        run: |
          curl https://getsubstrate.io -sSf | bash -s -- --fast
          cd ./moonbeam
          ./scripts/init.sh

      - name: build the moonbeam binary
        run: |
          source $HOME/.cargo/env
          cd ./moonbeam
          cargo build --release

      - name: monkey test the prebuilt moonbeam binary
        run: ./moonbeam/target/release/moonbeam --version

      - name: zipup the binary
        run:  zip -mj ./moonbeam-${{ env.MOONBEAM_BINARY_TAG }}-${{ matrix.os }}.zip ./moonbeam/target/release/moonbeam
     
      # - name: sha256sum the binary
      #   run: |
      #     sha256sum -b ./moonbeam-${{ env.MOONBEAM_BINARY_TAG }}-${{ matrix.os }}.zip >> /tmp/sha256sums
      #     # TODO add the sha sums file to the release somehow

      - name: download the release upload url artifact
        uses: actions/download-artifact@v2.0.8
        with:
          name: release_upload_url

      - name: set the release upload url as an env var
        run: echo "RELEASE_UPLOAD_URL=$(<./release_upload_url.txt)" >> $GITHUB_ENV

      - name: upload the prebuilt binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: ./moonbeam-${{ env.MOONBEAM_BINARY_TAG }}-${{ matrix.os }}.zip
          asset_name: moonbeam-${{ env.MOONBEAM_BINARY_TAG }}-${{ matrix.os }}.zip
          asset_content_type: application/zip